### ISSUE TITLE
"break this into smaller pieces soon"

### ISSUE THREAD

**Issue by fregante** [jondashkyle/mediaSize#2]
Hello! I just made a nano module that only takes care of calculating the scale/size/margins: https://github.com/bfred-it/intrinsic-scale

Interested in integrating it? It would replace about 100 lines of [index.js](https://github.com/jondashkyle/mediaSize/blob/master/index.js) with <40 of 
[intrinsic-scale](https://github.com/bfred-it/intrinsic-scale/blob/master/dist/intrinsic-scale.node.js)

**Comment by bfred-it** [comment]
There's an even smaller package that mine redirects to now: https://github.com/sroucheray/contain-cover/blob/master/contain-cover.js

Interested in implementing it?
